- name: Check if liqoctl is already installed
  shell: liqoctl -v
  register: liqoctl_already_installed
  ignore_errors: true

- name: Download and install liqoctl
  shell: |
    curl -LO "https://github.com/liqotech/liqo/releases/download/v1.0.0/liqoctl-linux-amd64"
    chmod +x liqoctl-linux-amd64
    sudo mv liqoctl-linux-amd64 /usr/local/bin/liqoctl
  when: liqoctl_already_installed.rc != 0

- name: Install liqoctl
  shell: 'sudo install -o root -g root -m 0755 liqoctl /usr/local/bin/liqoctl'
  when: liqoctl_already_installed.rc != 0

- name: Check if liqo is already installed
  shell: liqoctl version
  register: liqo_already_installed
  ignore_errors: true

- name: Check if Network resource exists
  shell: kubectl get network networks
  register: network_resource
  ignore_errors: true

- name: Create Network resource for Liqo
  shell: |
    kubectl apply -f - <<EOF
    apiVersion: ipam.liqo.io/v1alpha1
    kind: Network
    metadata:
      name: networks
    spec:
      cidr: "10.42.0.0/16"
      preAllocated: 100
    EOF
  when: network_resource.rc != 0


- name: Install Liqo       
  shell: 'sudo liqoctl install k3s --kubeconfig=/etc/rancher/k3s/k3s.yaml --enable-metrics --set controllerManager.metrics.serviceMonitor.enabled=true --set metrics.prometheusOperator.enabled=true'
  when: liqo_already_installed.rc != 0
